---
apiVersion: v1
kind: Service
metadata:
  name: dns-service
  namespace: dns
spec:
  clusterIP: None
  ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
  selector:
    app: dns-service
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dns-deploy
  namespace: dns
  labels:
    app: dns-service
spec:
  selector:
    matchLabels:
      app: dns-service
  template:
    metadata:
      labels:
        app: dns-service
    spec:
      restartPolicy: Always
      containers:
        - name: server
          image: registry.gitlab.com/kamackay/dns:latest
          imagePullPolicy: Always
          ports:
            - name: dns
              containerPort: 53
---
